conversation/urls.py
from django.urls import path

from . import views

app_name ='conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('pay/', views.pay, name='pay'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models

class MyModel(models.Model):
    name = models.CharField(max_length=100, default='default value')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name
 

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
     
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

# from django.contrib.auth import logout as logouts

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse

def index(request):
    items = Item.objects.filter(is_sold=False)[0:12]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

def logout_user(request):
    logout(request)
    messages.success(request, ("You were logged out."))
    return redirect(reverse('core:index'))

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer async src=""></script>
    <title>{% block title %}{% endblock %} | Puddle</title>
    <!-- {% load static %} -->
    
      
</head>
<body class="font-serif">
    <nav class="px-6 py-6 flex justify-between items-center border-b border-grey-200">
        <a href="/" class="text-xl font-semibold">puddle</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500 hidden lg:inline-block">New Item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500 hidden lg:inline-block">Browser</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 hidden lg:inline-block">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700 hidden lg:inline-block">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-950 hidden lg:inline-block">Logout</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 hidden lg:inline-block">Sign Up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700 hidden lg:inline-block">Log in</a>
            {% endif %}
            
            
        </div>
        {% load static %}

                <div class="navbar lg:hidden">
                    <svg id="menu-icon" class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path id="menu-icon-path" d="M4 6H20M4 12H20M4 18H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                      
                   

    </nav>
    <div id="nav-links" class=" mb-10 hidden px-3">
        <a href="{% url 'item:new' %}" class="block text-lg font-semibold hover:text-gray-500 mt-6 text-center" id="new-item-link">New Item</a><br><hr>
        <a href="{% url 'item:items' %}" class="block mt-5 text-center mx-center text-lg font-semibold hover:text-gray-500">Browser</a><br><hr>

        {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="block mt-10 text-center px-6 py-3 mb-5 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" id="inbox-link">Inbox</a><br>
            <a href="{% url 'dashboard:index' %}" class="block text-center px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a><br>
            <a href="{% url 'core:logout' %}" class="block mt-5 text-center px-6 py-3 mb-10 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-950" id="inbox-link">Logout</a><br>
        {% else %}
            <a href="{% url 'core:signup' %}" class="block text-center px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 mt-10">Sign Up</a><br>
            <a href="{% url 'core:login' %}" class="block text-center px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a><br>
        {% endif %}
    </div>
</div>


    <div id="body-content" class="py-0">
        {% block content %}
        {% endblock %}
    </div>
   <footer class="py-6 px-6 bg-gray-500">
    <div class="flex justify-between">
    <div class="grid grid-cols-3 gap-3" >
        <div class="mx-10">
            <h3 class="mb-5 font-semibold text-gray-400">SHOP</h3>

            <ul class="space-y-2">
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Gift Card</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">store locator</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Refer a friend</a></li>
            </ul>
        </div>

        <div class="mx-10">
            <h3 class="mb-5 font-semibold text-gray-400">HELP</h3>

            <ul class="space-y-2">
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact Us</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">FAQ</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Accessiblity</a></li>
            </ul>
        </div>

        <div class="mx-10">
            <h3 class="mb-5 font-semibold text-gray-400">ABOUT</h3>

            <ul class="space-y-2">
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Our Story</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Wholesale</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Press</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Careers</a></li>
            </ul>
        </div>
    </div>
    <div class=" sm:block hidden pr-10">
        <div>
            <p>Sign Up to get 10% of your first order</p>
        <form action=".">
            {% csrf_token %}
            <div class="flex justify-between">
            <input type="email" id="email-address" class="border border-gray-300 rounded-3xl focus:outline-none focus:border-blue-500 h-12 w-full my-3 pl-5 py-5" placeholder="Your Email Address" required />
            <button class="px-6 ml-5 mt-3 h-12 text-lg font-semibold bg-teal-500 text-white rounded-3xl hover:bg-teal-700">Subscribe</button>
            </div>
        </form>
        </div>
        <div class=" w-40 flex justify-between mt-4">
        <a href="https://www.linkedin.com/in/daniel-okoroafor-61b321208" target="_blank">
            <svg id="linkedin-icon" class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path id="linkedin-icon-path" d="M20 4H4C2.897 4 2 4.897 2 6V20C2 21.103 2.897 22 4 22H20C21.103 22 22 21.103 22 20V6C22 4.897 21.103 4 20 4ZM9 18H6V9H9V18ZM7.5 7.5C6.675 7.5 6 6.825 6 6C6 5.175 6.675 4.5 7.5 4.5C8.325 4.5 9 5.175 9 6C9 6.825 8.325 7.5 7.5 7.5ZM18 18H15V13.5C15 12.12 13.88 11 12.5 11C11.12 11 10 12.12 10 13.5V18H7V9H10V10.56C10.395 9.74 11.38 9 12.5 9C14.985 9 17 11.015 17 13.5V18Z" fill="blue" />
            </svg>
        </a>
        
        <a href="https://github.com/OkoroaforDaniel" target="_blank">
            <svg id="github-icon" class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path id="github-icon-path" d="M12 2C6.477 2 2 6.477 2 12C2 15.866 4.242 19.416 8.06 20.732C8.66 20.875 8.913 20.489 8.913 20.162C8.913 19.902 8.901 19.184 8.895 18.104C5.957 18.583 4.96 17.191 4.96 17.191C4.376 16.125 3.582 15.811 3.582 15.811C2.495 15.149 3.645 15.169 3.645 15.169C4.796 15.235 5.318 16.321 5.318 16.321C6.246 18.001 7.775 17.498 8.974 17.202C9.065 16.854 9.278 16.587 9.531 16.413C7.079 16.121 4.336 14.875 4.336 10.524C4.336 9.327 4.773 8.364 5.464 7.633C5.373 7.413 5.079 6.2 5.629 4.708C5.629 4.708 6.743 4.409 8.895 5.91C9.873 5.629 10.936 5.489 12 5.484C13.064 5.489 14.127 5.629 15.105 5.91C17.257 4.409 18.371 4.708 18.371 4.708C18.921 6.2 18.628 7.413 18.537 7.633C19.228 8.364 19.664 9.327 19.664 10.524C19.664 14.886 16.914 16.126 14.456 16.413C14.862 16.681 15.21 17.133 15.21 18.199C15.21 19.63 15.195 20.772 15.195 20.982C15.195 21.32 15.44 21.781 15.91 21.642C19.759 19.423 22 15.872 22 12C22 6.477 17.523 2 12 2Z" fill="currentColor"/>
            </svg>
        </a>
        </div>
    </div>
    </div>

    <div>
        <ul class="w-90 mt-10 sm:flex-none sm:justify-between-none">
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Service</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">privacy policy</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Don't sell my Information</a></li>
        </ul>
    </div>
   
</footer>

<!-- <script type="text/javascript" src="{% static 'js/nav.js' %}"></script> -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
    const menuIcon = document.getElementById('menu-icon');
    const menuIconPath = document.getElementById('menu-icon-path');
    const navLinks = document.getElementById('nav-links');
    const bodyContent = document.getElementById('body-content');

    menuIcon.addEventListener('click', () => {
    navLinks.classList.toggle('hidden');
    bodyContent.classList.toggle('hidden');
    menuIconPath.setAttribute('d', navLinks.classList.contains('hidden') ? 'M4 6H20M4 12H20M4 18H20' : 'M6 18L18 6M6 6l12 12');
    });
});
</script>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1>Contact</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}

    <div class="mt-6 px-6 py-12 ">
        <h2 class="text-xl mb-12 md:text-2xl text-center">Newest Items</h2>

        <div class="lg:grid lg:grid-cols-3 lg:gap-3">
            {% for item in items %}
                <div class="flex justify-center items-center mb-6">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl w-80 h-80 md:rounded-t-xl md:w-80 md:h-80">
                        </div>

                        <div class="p-2  rounded-b-xl w-30 h-20 md:w-80 md:h-40 md:p-6 bg-gray-100">
                            <h2 class="text-sm md:text-2xl">{{ item.name }}</h2>
                            <p class="text-xs text-gray-500 md:text-2xl">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 font-serif">
        <h2 class="text-xl mb-12 md:text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-sm md:text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} item</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div><hr class="bg-gray-700">

    <div class="px-6 py-12 bg-gray-100 font-serif">
        <h3 class="mb-5 font-semibold text-gray-500 text-center">About</h3>
        <p class="text-lg text-gray-400 text-center">
            As a passionate individual with an entrepreneurial spirit, I have always been fascinated by the power of technology 
            to bring people together and transform the way we live and do business. It was this fascination and my desire to create something meaningful that 
            inspired me to embark on a personal project: an online marketplace where people can buy a wide variety of products.
        </p>
    </div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="md:w-1/2  bg-gray-100 p-6 md:rounded-xl md:my-10 md:mx-auto">
    <h1 class="mb-6 text-3xl">Login in</h1>

    <form method="post" action=".">
        {% csrf_token %}


       <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
       </div>


        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>


    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for fields in form %}
                {{ field.errors }}
            {% endfor %}
            
            {{ form.non_field_errors }}
        </div>
    {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="md:w-1/2 mx-auto py-6 bg-gray-100 px-6 md:my-10 md:rounded-xl md:items-center">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}


       <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
       </div>

       <div class="mb-3">
        <label class="inline-block mb-2">Email</label><br>
        {{ form.email }}
   </div>

    <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br>
        {{ form.password1 }}
    </div>

    <div class="mb-3">
        <label class="inline-block mb-2">Repeat Password</label><br>
        {{ form.password2 }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for fields in form %}
                {{ field.errors }}
            {% endfor %}
            
            {{ form.non_field_errors }}
        </div>
    {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}